<a href="https://colab.research.google.com/github/sangcamap/house_price_prediction/blob/main/house_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd 
import numpy as np 

In [3]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/AI/House_price_prediction


Mounted at /content/drive
/content/drive/My Drive/AI/House_price_prediction


In [4]:
data = pd.read_csv('./train.csv', index_col= 'Id')
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [5]:
# data.columns
list(data.columns)

['MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'Enc

In [6]:
# Chọn lọc đặc trưng 

features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']

In [7]:
# Split dataset
# X: features
# Y: SalePrice


x = data[features]
y = data["SalePrice"]

In [8]:
x.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotRmsAbvGrd  
Id                
1              8  
2              6  
3              6  
4              7  
5              9

In [9]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

# 80% dùng để train, 20% để test
# Tách x và y ra thành x_train , x_valid, y_train, y_valid

x_train, x_valid, y_train, y_valid = train_test_split(x, y, train_size= 0.8, test_size = 0.2, random_state = 0)

In [11]:
x_train.shape

(1168, 7)

In [12]:
x.shape

(1460, 7)

In [28]:
from sklearn.tree import DecisionTreeRegressor 
# Mô hình cây quyết định 
# Ít phòng ngủ -> Giá ít hơn 

dt_model = DecisionTreeRegressor(random_state = 1)
dt_model.fit(x_train, y_train) 



DecisionTreeRegressor(random_state=1)

In [35]:
y_predict = dt_model.predict(x_valid) # Lấy 5 thằng đầu
y_predict[:5]

array([335000., 140200., 119000., 207500., 112000.])

In [36]:
# Trực quan giá trị

pd.DataFrame({'GTTT':  y_valid , 'GTDD': y_predict})

GTTT      GTDD
Id                    
530   200624  335000.0
492   133000  140200.0
460   110000  119000.0
280   192000  207500.0
656    88000  112000.0
...      ...       ...
327   324000  260400.0
441   555000  451950.0
1388  136000  107500.0
1324   82500   72500.0
62    101000   37900.0

[292 rows x 2 columns]

In [25]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor 
# Mô hình random forest

rf_model = RandomForestRegressor(random_state = 1) 
rf_model.fit(x_train, y_train)


RandomForestRegressor(random_state=1)

In [26]:
y_predict1 = rf_model.predict(x_valid)  
y_predict1[:5]   # lấy 4 giá trị đầu

array([271690., 155039., 122024., 188915.,  91147.])

In [27]:
pd.DataFrame({'GTTT':  y_valid , 'GTDD': y_predict1 })

GTTT       GTDD
Id                     
530   200624  271690.00
492   133000  155039.00
460   110000  122024.00
280   192000  188915.00
656    88000   91147.00
...      ...        ...
327   324000  275931.87
441   555000  478954.15
1388  136000  176038.00
1324   82500   78096.00
62    101000   81104.00

[292 rows x 2 columns]

In [22]:
x_valid.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                    
530    32668       1957      2515         0         3             4   
492     9490       1941       958       620         1             3   
460     7015       1950       979       224         1             3   
280    10005       1977      1156       866         2             4   
656     1680       1971       525       567         1             3   

     TotRmsAbvGrd  
Id                 
530             9  
492             5  
460             5  
280             8  
656             6

In [40]:
# Dự đoán không có trong list 

rf_model.predict([ [78888, 2000, 1000, 800, 3,	4,	9] ])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([198873.27])

In [38]:
# Kiểm tra model 
from sklearn.metrics import r2_score
r2_score(y_valid, y_predict)

0.5325376245236801

In [39]:
r2_score(y_valid, y_predict1)

0.7842596223072973